-- DELETE FROM photos;
ALTER TABLE photos AUTO_INCREMENT = 1;
INSERT INTO photos
                    (image_url, user_id) VALUES
						('http://oleta.net', 1),
						('https://fred.com', 3),
						('http://saige.com', 9),
						('http://vance.org', 9),
						('http://zena.com', 15),
						('http://kirk.org', 17),
						('http://lacy.biz', 29),
						('http://rico.biz', 65),
						('http://jody.biz', 65),
						('http://ted.info', 78),
						('http://cali.net', 88),
						('http://elijah.biz', 1),
						('http://aiden.org', 23),
						('http://einar.net', 26),
						('https://gust.net', 33),
						('https://lina.biz', 42),
						('http://euna.info', 43),
						('https://olga.org', 44),
						('https://roel.org', 51),
						('http://janie.com', 58),
						('http://myron.org', 58),
						('https://jane.net', 77),
						('http://adela.com', 88),
						('https://erik.com', 93),
						('https://shanon.org', 1),
						('http://malvina.org', 2),
						('https://maudie.org', 4),
						('http://darron.info', 8),
						('http://ignacio.net', 9),
						('http://collin.com', 16),
						('http://megane.biz', 23),
						('http://lionel.net', 23),
						('http://danyka.net', 23),
						('https://tito.name', 23),
						('http://verner.org', 23),
						('http://paxton.com', 28),
						('https://bryce.org', 29),
						('http://lottie.net', 29),
						('http://roger.info', 32),
						('https://brook.com', 33),
						('https://cesar.com', 39),
						('https://carey.com', 46),
						('http://kailee.org', 47),
						('https://edyth.com', 48),
						('https://adela.com', 55),
						('https://alia.name', 58),
						('http://pearl.info', 58),
						('https://lesly.com', 59),
						('http://delpha.com', 60),
						('http://devon.info', 64),
						('http://jarred.net', 77),
						('http://linnie.com', 77),
						('http://laney.name', 77),
						('http://emilie.net', 78),
						('http://mekhi.name', 88),
						('https://devan.com', 92),
						('http://freeda.biz', 94),
						('https://branson.biz', 2),
						('https://gerhard.biz', 4),
						('http://bonnie.info', 11),
						('http://kennith.net', 11),
						('https://adella.net', 12),
						('http://estevan.org', 15),
						('https://dejon.name', 20),
						('http://harvey.info', 23),
						('https://julian.net', 23),
						('http://fabiola.org', 29),
						('https://marian.biz', 29),
						('http://bridie.name', 33),
						('http://barton.name', 33),
						('https://aliyah.biz', 42),
						('https://maymie.net', 43),
						('http://joanie.name', 43),
						('http://whitney.net', 43),
						('http://shannon.org', 44),
						('https://isaias.biz', 50),
						('http://rosetta.net', 50),
						('https://aimee.info', 52),
						('http://kaleigh.biz', 59),
						('https://nolan.name', 64),
						('https://hilda.info', 65),
						('http://jovanny.net', 77),
						('http://keshawn.org', 78),
						('http://deontae.org', 86),
						('http://helena.name', 87),
						('http://violet.info', 87),
						('https://helmer.org', 96),
						('http://felicity.name', 3),
						('https://tyshawn.com', 12),
						('https://glenda.info', 13),
						('http://tressie.info', 15),
						('https://hershel.com', 16),
						('https://deondre.com', 17),
						('http://tristin.name', 17),
						('https://jarret.info', 26),
						('https://jacinto.org', 28),
						('https://trinity.biz', 28),
						('https://jensen.name', 30),
						('https://donavon.org', 44),
						('http://kendrick.net', 46),
						('http://lurline.info', 47),
						('http://quinten.info', 51),
						('https://dolores.org', 52),
						('https://demarco.com', 56),
						('http://jedediah.net', 59),
						('https://dameon.name', 62),
						('https://delbert.net', 63),
						('https://javonte.org', 72),
						('http://cynthia.info', 84),
						('http://princess.org', 85),
						('https://ruthie.info', 85),
						('http://germaine.org', 86),
						('https://mariano.net', 88),
						('https://blanche.net', 88),
						('https://maggie.info', 96),
						('https://cecilia.net', 96),
						('http://ryleigh.info', 99),
						('https://xzavier.org', 99),
						('https://kaela.name', 100),
						('http://dedrick.info', 100),
						('https://marcelino.com', 3),
						('https://brooklyn.name', 8),
						('https://modesta.info', 18),
						('https://earline.info', 51),
						('https://cathrine.com', 52),
						('https://carmella.com', 59),
						('https://malcolm.name', 59),
						('http://annabelle.org', 61),
						('https://julianne.org', 63),
						('http://germaine.name', 67),
						('http://penelope.info', 82),
						('https://dimitri.info', 84),
						('https://devonte.name', 88),
						('https://kathleen.biz', 95),
						('https://marianna.info', 50),
						('http://marcellus.info', 72),
						('https://madaline.name', 88),
						('https://llewellyn.info', 70),
						('https://celestino.name', 87);

INSERT INTO photos
                    (image_url, caption, user_id) VALUES
						('http://alena.net',"Be honest.", 12),
						('http://laila.info',"Be honest.", 47),
						('http://susie.info',"Be honest.", 86),
						('https://selina.name',"Eyes are never quite.", 2),
						('https://carolanne.com',"Eyes are never quite.", 32),
						('http://buddy.com',"Everyday is a second chance.", 47),
						('http://reva.com',"Sometimes silence is violent.", 69),
						('http://ralph.name',"Everyday is a second chance.", 12),
						('http://hollis.com',"Everyday is a second chance.", 86),
						('http://madison.net',"One does not simply Let it go.", 8),
						('https://kayden.biz',"Sometimes silence is violent.", 32),
						('http://ora.net',"Be who and what you want, period.", 64),
						('http://trever.org',"One does not simply Let it go.", 78),
						('https://darwin.net',"One does not simply Let it go.", 42),
						('http://lia.biz',"Life is better when you are laughing.", 46),
						('https://timmy.info',"You will never know until you go.", 86),
						('http://camille.name',"You will never know until you go.", 11),
						('https://kennedi.org',"Be who and what you want, period.", 29),
						('http://destini.net',"Be yourself; there’s no one better.", 88),
						('http://rylan.biz',"Beauty is power; a smile is its sword.", 19),
						('http://kasandra.com',"Invest the now in tomorrow’s dream.", 26),
						('https://lila.biz',"Beauty is power; a smile is its sword.", 58),
						('https://elmore.org',"Home is not a place; it is a feeling.", 26),
						('https://celestine.name',"You will never know until you go.", 46),
						('http://ellen.info',"People always change after being hurt.", 72),
						('https://estell.info',"Home is not a place; it is a feeling.", 59),
						('http://garrison.name',"Life is better when you are laughing.", 43),
						('http://julia.info',"Things left unsaid stay with us forever.", 51),
						('https://humberto.org',"Life is better when you are laughing.", 82),
						('https://noble.net',"Things left unsaid stay with us forever.", 88),
						('http://remington.name',"Overthinking does kill your happiness.", 10),
						('https://fanny.net',"The question isn’t can you, it is will you?", 29),
						('https://vivien.com',"The question isn’t can you, it is will you?", 64),
						('https://lisa.com',"Live for the moments you cannot put into words.", 6),
						('http://ole.info',"If an opportunity does not knock, build a door!", 78),
						('https://reece.net',"If an opportunity does not knock, build a door!", 9),
						('https://brittany.org',"When the parents hate it, the kids love it!", 88),
						('https://seamus.org',"I may be quiet, but I have so much on my mind.", 51),
						('http://nigel.biz',"Covers up real feelings with aggressive sarcasm.", 87),
						('https://emilia.org',"I may be quiet, but I have so much on my mind.", 88),
						('http://charlie.com',"Live for the moments you cannot put into words.", 40),
						('https://evan.name',"They used to shout my name, now they whisper it.", 86),
						('http://dominic.biz',"Covers up real feelings with aggressive sarcasm.", 15),
						('https://abagail.com',"Birds born in a cage think flying is an illness.", 16),
						('https://clair.com',"I’ve found out that time can heal almost anything.", 16),
						('http://miracle.info',"A happy soul is the best shield for a cruel world.", 6),
						('http://arthur.name',"A happy soul is the best shield for a cruel world.", 38),
						('https://roberta.net',"Make mistakes; it is better than faking perfection.", 59),
						('https://colt.org',"Whatever you do in life, make sure it makes you happy.", 86),
						('https://darien.name',"Make mistakes; it is better than faking perfection.", 99),
						('https://roderick.name',"I’ve found out that time can heal almost anything.", 52),
						('https://dorcas.biz',"If it does not challenge you, it does not change you.", 65),
						('https://alisha.com',"Whatever you do in life, make sure it makes you happy.", 11),
						('http://americo.biz',"Whatever you do in life, make sure it makes you happy.", 47),
						('http://hettie.net',"Do not stop when you are tired. Stop when you are done.", 65),
						('http://jennie.com',"Don’t let anyone tell you that you are not strong enough.", 98),
						('http://emmet.com',"Some Girls want superman but walk past Clark Kent every day!", 6),
						('http://emmalee.org',"We’re happy, free, confused, and lonely at the same time.", 23),
						('http://dino.name',"Some Girls want superman but walk past Clark Kent every day!", 77),
						('https://cielo.info',"Behind every status, there is a secret message for someone.", 13),
						('http://terry.info',"Life is short. There is no time to leave important words unsaid.", 26),
						('http://victoria.biz',"Life is short. False statement. it is the longest thing you do.", 58),
						('https://geoffrey.info',"If your life got harder, Congratulations! You just leveled up.", 28),
						('http://stan.biz',"Life is not a problem to be solved, but a reality to be experienced.", 73),
						('http://nathan.net',"Love the people who saw you when you were invisible to everyone else.", 23),
						('http://emery.net',"There’s no such thing as dimness, only an unlucky deficiency of light.", 29),
						('https://trycia.com',"Life is not a problem to be solved, but a reality to be experienced.", 35),
						('http://ayden.name',"Love the people who saw you when you were invisible to everyone else.", 95),
						('http://kendall.biz',"Life is like riding a bicycle. To keep balance, you must keep moving.", 13),
						('https://holden.com',"Don’t talk, just act. Don’t say, just show. Don’t promise, just prove.", 27),
						('http://ephraim.com',"Don’t talk, just act. Don’t say, just show. Don’t promise, just prove.", 62),
						('https://ariel.net',"Do not give up. There is no such thing as an ending. Just a new beginning.", 31),
						('https://jennings.biz',"Do not give up. There is no such thing as an ending. Just a new beginning.", 1),
						('https://elenor.name',"Beautiful people are not always good, but good people are always beautiful.", 3),
						('https://jarret.name',"The saddest think about betrayal is that it never comes from your enemies.", 52),
						('https://clare.org',"If you live for other people’s acceptance you will die from their rejection.", 59),
						('https://elyssa.biz',"If you live for other people’s acceptance you will die from their rejection.", 97),
						('https://ford.biz',"Like it or not, you will eventually become a reflection of the company you keep.", 79),
						('http://lucio.org',"When you are writing the story of your life, Do not let anyone else hold the pen.", 86),
						('http://annie.name',"The most important thing is to enjoy your life to be happy it is all that matters.", 8),
						('https://mafalda.org',"You see a person’s true colors when you are no longer beneficial to their life.", 23),
						('http://howard.net',"We waste time looking for the perfect lover instead of creating the perfect love.", 86),
						('https://easter.net',"We waste time looking for the perfect lover instead of creating the perfect love.", 13),
						('http://golden.org',"The most important thing is to enjoy your life to be happy  it is all that matters.", 13),
						('https://karina.biz',"Keep smiling because life is a beautiful thing and there is so much to smile about.", 33),
						('http://florine.org',"Keep smiling because life is a beautiful thing and there is so much to smile about.", 72),
						('https://anahi.info',"A clever person solves a problem. A wise person avoids it. A dumb person creates it.", 72),
						('https://mac.org',"One of the biggest mistakes we make is assuming that other people think the way we think.", 6),
						('http://kenny.com',"More love is needed to say I hate you after a fight than that in confessing I love you.", 10),
						('http://boris.biz',"One of the biggest mistakes we make is assuming that other people think the way we think.", 38),
						('http://ayla.org',"Lives change like the weather. I hope you remember today is never too late to be brand new.", 97),
						('https://jessy.name',"Don’t worry if you haven’t found your true love, they’re just with someone else right now.", 64),
						('http://annamae.name',"I walk around like everything is fine, but deep down, inside my shoe, my sock is suing off.", 6),
						('http://sedrick.net',"Lives change like the weather. I hope you remember today is never too late to be brand new.", 59),
						('https://everette.biz',"I walk around like everything is fine, but deep down, inside my shoe, my sock is suing off.", 37),
						('https://norval.com',"Stop letting people, who do so little for you, control so much of your emotions in your life.", 63),
						('https://mariane.org',"Mom said life is similar to a container of chocolates, you never realize what you are gonna get.", 67),
						('https://margarita.info',"Mom said life is similar to a container of chocolates, you never realize what you are gonna get.", 32),
						('http://blanca.org',"You don’t always need a plan. Sometimes you just need to breathe, trust, let go and see what happens.", 60),
						('http://leo.com',"Don’t be afraid of death. Be afraid of wasted life. You don’t have to live forever; you just have to live.", 59),
						('https://woodrow.com',"Don’t be afraid of death. Be afraid of wasted life. You don’t have to live forever; you just have to live.", 23),
						('https://mariam.com',"Travel is more than the seeing of sights; it is a change that goes on, deep and permanent, in the ideas of living.", 35),
						('https://sherwood.net',"Travel is more than the seeing of sights; it is a change that goes on, deep and permanent, in the ideas of living.", 4),
						('http://virginia.org',"Stop being a zombie. Find something that you are excited about in your life; otherwise, you are just walking dead.", 30),
						('https://sid.biz',"Learn to appreciate the people who want to be in your life and stop stressing over people who don’t want to be in your life.", 92),
						('http://ruben.net',"Insecurities can make even the smartest and most beautiful woman foolishly question herself despite how amazing she truly is.", 58),
						('https://quinn.biz',"Life is like a box of chocolate; sometimes you just dig out the good center parts and leave all the undesirable rest to waste.", 2),
						('https://noemie.com',"Insecurities can make even the smartest and most beautiful woman foolishly question herself despite how amazing she truly is.", 19),
						('http://sheila.com',"Life is like a box of chocolate; sometimes you just dig out the good center parts and leave all the undesirable rest to waste.", 67),
						('https://jarrett.name',"Insecurities can make even the smartest and most beautiful woman foolishly question herself despite how amazing she truly is.", 92),
						('http://rickey.name',"Life is not measured by the number of breaths you take, but the moments that take your breath away. So make those moments count!", 58),
						('https://jasmin.biz',"Someday someone is going to look at you like you are the best thing in the world. It takes time, but it will happen. Be patient.", 63),
						('https://jadyn.name',"Life is not measured by the number of breaths you take, but the moments that take your breath away. So make those moments count!", 93),
						('https://rigoberto.net',"Life is not measured by the number of breaths you take, but the moments that take your breath away. So make those moments count!", 22),
						('https://henderson.com',"Learn the difference, my friends.", 11),
						('http://moses.biz',"Just when you think you know it all, you realize you did not know a thing. That is when you will understand the beauty of life.", 44),
						('http://kurtis.info',"Just when you think you know it all, you realize you did not know a thing. That is when you will understand the beauty of life.", 10),
                        ('http://vacay.info',"Good days and cold waters.", 10);
-- DELETE from photos;
-- SELECT * from photos;
